// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_reduce_accum2_ii_is_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        ap_return,
        grp_fu_101_p_din0,
        grp_fu_101_p_din1,
        grp_fu_101_p_opcode,
        grp_fu_101_p_dout0,
        grp_fu_101_p_ce
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] A_address0;
output   A_ce0;
input  [31:0] A_q0;
output  [31:0] ap_return;
output  [31:0] grp_fu_101_p_din0;
output  [31:0] grp_fu_101_p_din1;
output  [1:0] grp_fu_101_p_opcode;
input  [31:0] grp_fu_101_p_dout0;
output   grp_fu_101_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ap_return;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_start;
wire    grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_done;
wire    grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_idle;
wire    grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_ready;
wire   [31:0] grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_accum_1_0_out;
wire    grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_accum_1_0_out_ap_vld;
wire   [31:0] grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_accum_0_0_out;
wire    grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_accum_0_0_out_ap_vld;
wire    grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_start;
wire    grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_done;
wire    grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_idle;
wire    grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_ready;
wire   [9:0] grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_A_address0;
wire    grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_A_ce0;
wire   [31:0] grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_accum_1_2_out;
wire    grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_accum_1_2_out_ap_vld;
wire   [31:0] grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_accum_0_2_out;
wire    grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_accum_0_2_out_ap_vld;
wire   [31:0] grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_grp_fu_50_p_din0;
wire   [31:0] grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_grp_fu_50_p_din1;
wire   [1:0] grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_grp_fu_50_p_opcode;
wire    grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_grp_fu_50_p_ce;
reg    grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [31:0] grp_fu_50_p0;
reg   [31:0] grp_fu_50_p1;
reg    grp_fu_50_ce;
reg   [31:0] ap_return_preg;
wire    ap_CS_fsm_state12;
reg   [11:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_start_reg = 1'b0;
#0 grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_start_reg = 1'b0;
#0 ap_return_preg = 32'd0;
end

top_reduce_accum2_ii_is_4_Pipeline_1 grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_start),
    .ap_done(grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_done),
    .ap_idle(grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_idle),
    .ap_ready(grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_ready),
    .accum_1_0_out(grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_accum_1_0_out),
    .accum_1_0_out_ap_vld(grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_accum_1_0_out_ap_vld),
    .accum_0_0_out(grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_accum_0_0_out),
    .accum_0_0_out_ap_vld(grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_accum_0_0_out_ap_vld)
);

top_reduce_accum2_ii_is_4_Pipeline_accum2 grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_start),
    .ap_done(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_done),
    .ap_idle(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_idle),
    .ap_ready(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_ready),
    .accum_1_0_reload(grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_accum_1_0_out),
    .accum_0_0_reload(grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_accum_0_0_out),
    .A_address0(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_A_address0),
    .A_ce0(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_A_ce0),
    .A_q0(A_q0),
    .accum_1_2_out(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_accum_1_2_out),
    .accum_1_2_out_ap_vld(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_accum_1_2_out_ap_vld),
    .accum_0_2_out(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_accum_0_2_out),
    .accum_0_2_out_ap_vld(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_accum_0_2_out_ap_vld),
    .grp_fu_50_p_din0(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_grp_fu_50_p_din0),
    .grp_fu_50_p_din1(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_grp_fu_50_p_din1),
    .grp_fu_50_p_opcode(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_grp_fu_50_p_opcode),
    .grp_fu_50_p_dout0(grp_fu_101_p_dout0),
    .grp_fu_50_p_ce(grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_grp_fu_50_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            ap_return_preg <= grp_fu_101_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_start_reg <= 1'b1;
        end else if ((grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_ready == 1'b1)) begin
            grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_start_reg <= 1'b1;
        end else if ((grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_ready == 1'b1)) begin
            grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_start_reg <= 1'b0;
        end
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_return = grp_fu_101_p_dout0;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_50_ce = grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_grp_fu_50_p_ce;
    end else begin
        grp_fu_50_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_50_p0 = grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_grp_fu_50_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_50_p0 = grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_accum_0_2_out;
    end else begin
        grp_fu_50_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_50_p1 = grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_grp_fu_50_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_50_p1 = grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_accum_1_2_out;
    end else begin
        grp_fu_50_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_A_address0;

assign A_ce0 = grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_A_ce0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_fu_101_p_ce = grp_fu_50_ce;

assign grp_fu_101_p_din0 = grp_fu_50_p0;

assign grp_fu_101_p_din1 = grp_fu_50_p1;

assign grp_fu_101_p_opcode = 2'd0;

assign grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_start = grp_reduce_accum2_ii_is_4_Pipeline_1_fu_34_ap_start_reg;

assign grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_start = grp_reduce_accum2_ii_is_4_Pipeline_accum2_fu_40_ap_start_reg;

endmodule //top_reduce_accum2_ii_is_4
