// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_top,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.857200,HLS_SYN_LAT=28843,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2233,HLS_SYN_LUT=2697,HLS_VERSION=2021_2}" *)

module top (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        B,
        B_ap_vld
);

parameter    ap_ST_fsm_state1 = 33'd1;
parameter    ap_ST_fsm_state2 = 33'd2;
parameter    ap_ST_fsm_state3 = 33'd4;
parameter    ap_ST_fsm_state4 = 33'd8;
parameter    ap_ST_fsm_state5 = 33'd16;
parameter    ap_ST_fsm_state6 = 33'd32;
parameter    ap_ST_fsm_state7 = 33'd64;
parameter    ap_ST_fsm_state8 = 33'd128;
parameter    ap_ST_fsm_state9 = 33'd256;
parameter    ap_ST_fsm_state10 = 33'd512;
parameter    ap_ST_fsm_state11 = 33'd1024;
parameter    ap_ST_fsm_state12 = 33'd2048;
parameter    ap_ST_fsm_state13 = 33'd4096;
parameter    ap_ST_fsm_state14 = 33'd8192;
parameter    ap_ST_fsm_state15 = 33'd16384;
parameter    ap_ST_fsm_state16 = 33'd32768;
parameter    ap_ST_fsm_state17 = 33'd65536;
parameter    ap_ST_fsm_state18 = 33'd131072;
parameter    ap_ST_fsm_state19 = 33'd262144;
parameter    ap_ST_fsm_state20 = 33'd524288;
parameter    ap_ST_fsm_state21 = 33'd1048576;
parameter    ap_ST_fsm_state22 = 33'd2097152;
parameter    ap_ST_fsm_state23 = 33'd4194304;
parameter    ap_ST_fsm_state24 = 33'd8388608;
parameter    ap_ST_fsm_state25 = 33'd16777216;
parameter    ap_ST_fsm_state26 = 33'd33554432;
parameter    ap_ST_fsm_state27 = 33'd67108864;
parameter    ap_ST_fsm_state28 = 33'd134217728;
parameter    ap_ST_fsm_state29 = 33'd268435456;
parameter    ap_ST_fsm_state30 = 33'd536870912;
parameter    ap_ST_fsm_state31 = 33'd1073741824;
parameter    ap_ST_fsm_state32 = 33'd2147483648;
parameter    ap_ST_fsm_state33 = 33'd4294967296;

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] A_address0;
output   A_ce0;
input  [31:0] A_q0;
output  [31:0] B;
output   B_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] A_address0;
reg A_ce0;
reg B_ap_vld;

(* fsm_encoding = "none" *) reg   [32:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] grp_fu_65_p2;
reg   [31:0] reg_71;
wire    ap_CS_fsm_state9;
wire    grp_reduce_accum2_ii_is_4_fu_47_ap_ready;
wire    grp_reduce_accum2_ii_is_4_fu_47_ap_done;
wire    ap_CS_fsm_state17;
wire    grp_reduce_accum4_ii_is_3_fu_53_ap_ready;
wire    grp_reduce_accum4_ii_is_3_fu_53_ap_done;
wire    ap_CS_fsm_state25;
wire    grp_reduce_accum8_ii_is_1_fu_59_ap_ready;
wire    grp_reduce_accum8_ii_is_1_fu_59_ap_done;
wire   [31:0] grp_reduce_basic_ii_is_3_fu_41_ap_return;
wire    ap_CS_fsm_state2;
wire   [31:0] grp_reduce_accum2_ii_is_4_fu_47_ap_return;
reg   [31:0] tmp_1_reg_86;
wire   [31:0] grp_reduce_accum4_ii_is_3_fu_53_ap_return;
reg   [31:0] tmp_2_reg_91;
wire   [31:0] grp_reduce_accum8_ii_is_1_fu_59_ap_return;
reg   [31:0] tmp_3_reg_96;
wire    grp_reduce_basic_ii_is_3_fu_41_ap_start;
wire    grp_reduce_basic_ii_is_3_fu_41_ap_done;
wire    grp_reduce_basic_ii_is_3_fu_41_ap_idle;
wire    grp_reduce_basic_ii_is_3_fu_41_ap_ready;
wire   [9:0] grp_reduce_basic_ii_is_3_fu_41_A_address0;
wire    grp_reduce_basic_ii_is_3_fu_41_A_ce0;
wire   [31:0] grp_reduce_basic_ii_is_3_fu_41_grp_fu_101_p_din0;
wire   [31:0] grp_reduce_basic_ii_is_3_fu_41_grp_fu_101_p_din1;
wire   [1:0] grp_reduce_basic_ii_is_3_fu_41_grp_fu_101_p_opcode;
wire    grp_reduce_basic_ii_is_3_fu_41_grp_fu_101_p_ce;
wire    grp_reduce_accum2_ii_is_4_fu_47_ap_start;
wire    grp_reduce_accum2_ii_is_4_fu_47_ap_idle;
wire   [9:0] grp_reduce_accum2_ii_is_4_fu_47_A_address0;
wire    grp_reduce_accum2_ii_is_4_fu_47_A_ce0;
wire   [31:0] grp_reduce_accum2_ii_is_4_fu_47_grp_fu_101_p_din0;
wire   [31:0] grp_reduce_accum2_ii_is_4_fu_47_grp_fu_101_p_din1;
wire   [1:0] grp_reduce_accum2_ii_is_4_fu_47_grp_fu_101_p_opcode;
wire    grp_reduce_accum2_ii_is_4_fu_47_grp_fu_101_p_ce;
wire    grp_reduce_accum4_ii_is_3_fu_53_ap_start;
wire    grp_reduce_accum4_ii_is_3_fu_53_ap_idle;
wire   [9:0] grp_reduce_accum4_ii_is_3_fu_53_A_address0;
wire    grp_reduce_accum4_ii_is_3_fu_53_A_ce0;
wire   [31:0] grp_reduce_accum4_ii_is_3_fu_53_grp_fu_101_p_din0;
wire   [31:0] grp_reduce_accum4_ii_is_3_fu_53_grp_fu_101_p_din1;
wire   [1:0] grp_reduce_accum4_ii_is_3_fu_53_grp_fu_101_p_opcode;
wire    grp_reduce_accum4_ii_is_3_fu_53_grp_fu_101_p_ce;
wire    grp_reduce_accum8_ii_is_1_fu_59_ap_start;
wire    grp_reduce_accum8_ii_is_1_fu_59_ap_idle;
wire   [9:0] grp_reduce_accum8_ii_is_1_fu_59_A_address0;
wire    grp_reduce_accum8_ii_is_1_fu_59_A_ce0;
wire   [31:0] grp_reduce_accum8_ii_is_1_fu_59_grp_fu_101_p_din0;
wire   [31:0] grp_reduce_accum8_ii_is_1_fu_59_grp_fu_101_p_din1;
wire   [1:0] grp_reduce_accum8_ii_is_1_fu_59_grp_fu_101_p_opcode;
wire    grp_reduce_accum8_ii_is_1_fu_59_grp_fu_101_p_ce;
reg    grp_reduce_basic_ii_is_3_fu_41_ap_start_reg;
reg    grp_reduce_accum2_ii_is_4_fu_47_ap_start_reg;
wire    ap_CS_fsm_state8;
reg    grp_reduce_accum4_ii_is_3_fu_53_ap_start_reg;
wire    ap_CS_fsm_state16;
reg    grp_reduce_accum8_ii_is_1_fu_59_ap_start_reg;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state33;
reg   [31:0] grp_fu_65_p0;
reg   [31:0] grp_fu_65_p1;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state26;
reg    grp_fu_65_ce;
wire   [31:0] grp_fu_101_p2;
reg   [31:0] grp_fu_101_p0;
reg   [31:0] grp_fu_101_p1;
reg    grp_fu_101_ce;
reg   [32:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
reg    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 33'd1;
#0 grp_reduce_basic_ii_is_3_fu_41_ap_start_reg = 1'b0;
#0 grp_reduce_accum2_ii_is_4_fu_47_ap_start_reg = 1'b0;
#0 grp_reduce_accum4_ii_is_3_fu_53_ap_start_reg = 1'b0;
#0 grp_reduce_accum8_ii_is_1_fu_59_ap_start_reg = 1'b0;
end

top_reduce_basic_ii_is_3 grp_reduce_basic_ii_is_3_fu_41(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reduce_basic_ii_is_3_fu_41_ap_start),
    .ap_done(grp_reduce_basic_ii_is_3_fu_41_ap_done),
    .ap_idle(grp_reduce_basic_ii_is_3_fu_41_ap_idle),
    .ap_ready(grp_reduce_basic_ii_is_3_fu_41_ap_ready),
    .A_address0(grp_reduce_basic_ii_is_3_fu_41_A_address0),
    .A_ce0(grp_reduce_basic_ii_is_3_fu_41_A_ce0),
    .A_q0(A_q0),
    .ap_return(grp_reduce_basic_ii_is_3_fu_41_ap_return),
    .grp_fu_101_p_din0(grp_reduce_basic_ii_is_3_fu_41_grp_fu_101_p_din0),
    .grp_fu_101_p_din1(grp_reduce_basic_ii_is_3_fu_41_grp_fu_101_p_din1),
    .grp_fu_101_p_opcode(grp_reduce_basic_ii_is_3_fu_41_grp_fu_101_p_opcode),
    .grp_fu_101_p_dout0(grp_fu_101_p2),
    .grp_fu_101_p_ce(grp_reduce_basic_ii_is_3_fu_41_grp_fu_101_p_ce)
);

top_reduce_accum2_ii_is_4 grp_reduce_accum2_ii_is_4_fu_47(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reduce_accum2_ii_is_4_fu_47_ap_start),
    .ap_done(grp_reduce_accum2_ii_is_4_fu_47_ap_done),
    .ap_idle(grp_reduce_accum2_ii_is_4_fu_47_ap_idle),
    .ap_ready(grp_reduce_accum2_ii_is_4_fu_47_ap_ready),
    .A_address0(grp_reduce_accum2_ii_is_4_fu_47_A_address0),
    .A_ce0(grp_reduce_accum2_ii_is_4_fu_47_A_ce0),
    .A_q0(A_q0),
    .ap_return(grp_reduce_accum2_ii_is_4_fu_47_ap_return),
    .grp_fu_101_p_din0(grp_reduce_accum2_ii_is_4_fu_47_grp_fu_101_p_din0),
    .grp_fu_101_p_din1(grp_reduce_accum2_ii_is_4_fu_47_grp_fu_101_p_din1),
    .grp_fu_101_p_opcode(grp_reduce_accum2_ii_is_4_fu_47_grp_fu_101_p_opcode),
    .grp_fu_101_p_dout0(grp_fu_101_p2),
    .grp_fu_101_p_ce(grp_reduce_accum2_ii_is_4_fu_47_grp_fu_101_p_ce)
);

top_reduce_accum4_ii_is_3 grp_reduce_accum4_ii_is_3_fu_53(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reduce_accum4_ii_is_3_fu_53_ap_start),
    .ap_done(grp_reduce_accum4_ii_is_3_fu_53_ap_done),
    .ap_idle(grp_reduce_accum4_ii_is_3_fu_53_ap_idle),
    .ap_ready(grp_reduce_accum4_ii_is_3_fu_53_ap_ready),
    .A_address0(grp_reduce_accum4_ii_is_3_fu_53_A_address0),
    .A_ce0(grp_reduce_accum4_ii_is_3_fu_53_A_ce0),
    .A_q0(A_q0),
    .ap_return(grp_reduce_accum4_ii_is_3_fu_53_ap_return),
    .grp_fu_101_p_din0(grp_reduce_accum4_ii_is_3_fu_53_grp_fu_101_p_din0),
    .grp_fu_101_p_din1(grp_reduce_accum4_ii_is_3_fu_53_grp_fu_101_p_din1),
    .grp_fu_101_p_opcode(grp_reduce_accum4_ii_is_3_fu_53_grp_fu_101_p_opcode),
    .grp_fu_101_p_dout0(grp_fu_101_p2),
    .grp_fu_101_p_ce(grp_reduce_accum4_ii_is_3_fu_53_grp_fu_101_p_ce)
);

top_reduce_accum8_ii_is_1 grp_reduce_accum8_ii_is_1_fu_59(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reduce_accum8_ii_is_1_fu_59_ap_start),
    .ap_done(grp_reduce_accum8_ii_is_1_fu_59_ap_done),
    .ap_idle(grp_reduce_accum8_ii_is_1_fu_59_ap_idle),
    .ap_ready(grp_reduce_accum8_ii_is_1_fu_59_ap_ready),
    .A_address0(grp_reduce_accum8_ii_is_1_fu_59_A_address0),
    .A_ce0(grp_reduce_accum8_ii_is_1_fu_59_A_ce0),
    .A_q0(A_q0),
    .ap_return(grp_reduce_accum8_ii_is_1_fu_59_ap_return),
    .grp_fu_101_p_din0(grp_reduce_accum8_ii_is_1_fu_59_grp_fu_101_p_din0),
    .grp_fu_101_p_din1(grp_reduce_accum8_ii_is_1_fu_59_grp_fu_101_p_din1),
    .grp_fu_101_p_opcode(grp_reduce_accum8_ii_is_1_fu_59_grp_fu_101_p_opcode),
    .grp_fu_101_p_dout0(grp_fu_101_p2),
    .grp_fu_101_p_ce(grp_reduce_accum8_ii_is_1_fu_59_grp_fu_101_p_ce)
);

top_fadd_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_8_full_dsp_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_65_p0),
    .din1(grp_fu_65_p1),
    .ce(grp_fu_65_ce),
    .dout(grp_fu_65_p2)
);

top_fadd_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_8_full_dsp_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_101_p0),
    .din1(grp_fu_101_p1),
    .ce(grp_fu_101_ce),
    .dout(grp_fu_101_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reduce_accum2_ii_is_4_fu_47_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_reduce_accum2_ii_is_4_fu_47_ap_start_reg <= 1'b1;
        end else if ((grp_reduce_accum2_ii_is_4_fu_47_ap_ready == 1'b1)) begin
            grp_reduce_accum2_ii_is_4_fu_47_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reduce_accum4_ii_is_3_fu_53_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_reduce_accum4_ii_is_3_fu_53_ap_start_reg <= 1'b1;
        end else if ((grp_reduce_accum4_ii_is_3_fu_53_ap_ready == 1'b1)) begin
            grp_reduce_accum4_ii_is_3_fu_53_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reduce_accum8_ii_is_1_fu_59_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state24)) begin
            grp_reduce_accum8_ii_is_1_fu_59_ap_start_reg <= 1'b1;
        end else if ((grp_reduce_accum8_ii_is_1_fu_59_ap_ready == 1'b1)) begin
            grp_reduce_accum8_ii_is_1_fu_59_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reduce_basic_ii_is_3_fu_41_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_reduce_basic_ii_is_3_fu_41_ap_start_reg <= 1'b1;
        end else if ((grp_reduce_basic_ii_is_3_fu_41_ap_ready == 1'b1)) begin
            grp_reduce_basic_ii_is_3_fu_41_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((grp_reduce_accum8_ii_is_1_fu_59_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25)) | ((grp_reduce_accum4_ii_is_3_fu_53_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17)) | ((grp_reduce_accum2_ii_is_4_fu_47_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        reg_71 <= grp_fu_65_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tmp_1_reg_86 <= grp_reduce_accum2_ii_is_4_fu_47_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        tmp_2_reg_91 <= grp_reduce_accum4_ii_is_3_fu_53_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        tmp_3_reg_96 <= grp_reduce_accum8_ii_is_1_fu_59_ap_return;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        A_address0 = grp_reduce_accum8_ii_is_1_fu_59_A_address0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        A_address0 = grp_reduce_accum4_ii_is_3_fu_53_A_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_address0 = grp_reduce_accum2_ii_is_4_fu_47_A_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_address0 = grp_reduce_basic_ii_is_3_fu_41_A_address0;
    end else begin
        A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        A_ce0 = grp_reduce_accum8_ii_is_1_fu_59_A_ce0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        A_ce0 = grp_reduce_accum4_ii_is_3_fu_53_A_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        A_ce0 = grp_reduce_accum2_ii_is_4_fu_47_A_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        A_ce0 = grp_reduce_basic_ii_is_3_fu_41_A_ce0;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        B_ap_vld = 1'b1;
    end else begin
        B_ap_vld = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_reduce_accum4_ii_is_3_fu_53_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

always @ (*) begin
    if ((grp_reduce_accum8_ii_is_1_fu_59_ap_done == 1'b0)) begin
        ap_ST_fsm_state25_blk = 1'b1;
    end else begin
        ap_ST_fsm_state25_blk = 1'b0;
    end
end

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((grp_reduce_basic_ii_is_3_fu_41_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_reduce_accum2_ii_is_4_fu_47_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_101_ce = grp_reduce_accum8_ii_is_1_fu_59_grp_fu_101_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_101_ce = grp_reduce_accum4_ii_is_3_fu_53_grp_fu_101_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_101_ce = grp_reduce_accum2_ii_is_4_fu_47_grp_fu_101_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_101_ce = grp_reduce_basic_ii_is_3_fu_41_grp_fu_101_p_ce;
    end else begin
        grp_fu_101_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_101_p0 = grp_reduce_accum8_ii_is_1_fu_59_grp_fu_101_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_101_p0 = grp_reduce_accum4_ii_is_3_fu_53_grp_fu_101_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_101_p0 = grp_reduce_accum2_ii_is_4_fu_47_grp_fu_101_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_101_p0 = grp_reduce_basic_ii_is_3_fu_41_grp_fu_101_p_din0;
    end else begin
        grp_fu_101_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_101_p1 = grp_reduce_accum8_ii_is_1_fu_59_grp_fu_101_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_101_p1 = grp_reduce_accum4_ii_is_3_fu_53_grp_fu_101_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_101_p1 = grp_reduce_accum2_ii_is_4_fu_47_grp_fu_101_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_101_p1 = grp_reduce_basic_ii_is_3_fu_41_grp_fu_101_p_din1;
    end else begin
        grp_fu_101_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | ((grp_reduce_accum8_ii_is_1_fu_59_ap_done == 1'b0) & (1'b1 == ap_CS_fsm_state25)) | ((grp_reduce_accum4_ii_is_3_fu_53_ap_done == 1'b0) & (1'b1 == ap_CS_fsm_state17)) | ((grp_reduce_accum2_ii_is_4_fu_47_ap_done == 1'b0) & (1'b1 == ap_CS_fsm_state9)) | ((1'b1 == ap_CS_fsm_state2) & (grp_reduce_basic_ii_is_3_fu_41_ap_done == 1'b0)))) begin
        grp_fu_65_ce = 1'b0;
    end else begin
        grp_fu_65_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_fu_65_p0 = reg_71;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_65_p0 = grp_reduce_basic_ii_is_3_fu_41_ap_return;
    end else begin
        grp_fu_65_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_65_p1 = tmp_3_reg_96;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_65_p1 = tmp_2_reg_91;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_65_p1 = tmp_1_reg_86;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_65_p1 = 32'd0;
    end else begin
        grp_fu_65_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_reduce_basic_ii_is_3_fu_41_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_reduce_accum2_ii_is_4_fu_47_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_reduce_accum4_ii_is_3_fu_53_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            if (((grp_reduce_accum8_ii_is_1_fu_59_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B = grp_fu_65_p2;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign grp_reduce_accum2_ii_is_4_fu_47_ap_start = grp_reduce_accum2_ii_is_4_fu_47_ap_start_reg;

assign grp_reduce_accum4_ii_is_3_fu_53_ap_start = grp_reduce_accum4_ii_is_3_fu_53_ap_start_reg;

assign grp_reduce_accum8_ii_is_1_fu_59_ap_start = grp_reduce_accum8_ii_is_1_fu_59_ap_start_reg;

assign grp_reduce_basic_ii_is_3_fu_41_ap_start = grp_reduce_basic_ii_is_3_fu_41_ap_start_reg;

endmodule //top
