// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_mmm_accum2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        C_address0,
        C_ce0,
        C_we0,
        C_d0,
        A_address0,
        A_ce0,
        A_q0,
        B_address0,
        B_ce0,
        B_q0,
        grp_fu_70_p_din0,
        grp_fu_70_p_din1,
        grp_fu_70_p_opcode,
        grp_fu_70_p_dout0,
        grp_fu_70_p_ce,
        grp_fu_74_p_din0,
        grp_fu_74_p_din1,
        grp_fu_74_p_dout0,
        grp_fu_74_p_ce
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_state2 = 22'd2;
parameter    ap_ST_fsm_state3 = 22'd4;
parameter    ap_ST_fsm_state4 = 22'd8;
parameter    ap_ST_fsm_state5 = 22'd16;
parameter    ap_ST_fsm_state6 = 22'd32;
parameter    ap_ST_fsm_state7 = 22'd64;
parameter    ap_ST_fsm_state8 = 22'd128;
parameter    ap_ST_fsm_state9 = 22'd256;
parameter    ap_ST_fsm_state10 = 22'd512;
parameter    ap_ST_fsm_state11 = 22'd1024;
parameter    ap_ST_fsm_state12 = 22'd2048;
parameter    ap_ST_fsm_state13 = 22'd4096;
parameter    ap_ST_fsm_state14 = 22'd8192;
parameter    ap_ST_fsm_state15 = 22'd16384;
parameter    ap_ST_fsm_state16 = 22'd32768;
parameter    ap_ST_fsm_state17 = 22'd65536;
parameter    ap_ST_fsm_state18 = 22'd131072;
parameter    ap_ST_fsm_state19 = 22'd262144;
parameter    ap_ST_fsm_state20 = 22'd524288;
parameter    ap_ST_fsm_state21 = 22'd1048576;
parameter    ap_ST_fsm_state22 = 22'd2097152;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] C_address0;
output   C_ce0;
output   C_we0;
output  [31:0] C_d0;
output  [14:0] A_address0;
output   A_ce0;
input  [63:0] A_q0;
output  [14:0] B_address0;
output   B_ce0;
input  [63:0] B_q0;
output  [31:0] grp_fu_70_p_din0;
output  [31:0] grp_fu_70_p_din1;
output  [1:0] grp_fu_70_p_opcode;
input  [31:0] grp_fu_70_p_dout0;
output   grp_fu_70_p_ce;
output  [31:0] grp_fu_74_p_din0;
output  [31:0] grp_fu_74_p_din1;
input  [31:0] grp_fu_74_p_dout0;
output   grp_fu_74_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg C_ce0;
reg C_we0;

(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] reg_131;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state21;
wire   [8:0] select_ln68_fu_197_p3;
reg   [8:0] select_ln68_reg_359;
wire    ap_CS_fsm_state4;
wire   [8:0] select_ln68_1_fu_206_p3;
reg   [8:0] select_ln68_1_reg_364;
wire   [0:0] trunc_ln75_fu_227_p1;
reg   [0:0] trunc_ln75_reg_369;
wire   [15:0] add_ln72_fu_236_p2;
reg   [15:0] add_ln72_reg_374;
wire    grp_mmm_accum2_Pipeline_1_fu_103_ap_start;
wire    grp_mmm_accum2_Pipeline_1_fu_103_ap_done;
wire    grp_mmm_accum2_Pipeline_1_fu_103_ap_idle;
wire    grp_mmm_accum2_Pipeline_1_fu_103_ap_ready;
wire   [31:0] grp_mmm_accum2_Pipeline_1_fu_103_accum_1_2_out;
wire    grp_mmm_accum2_Pipeline_1_fu_103_accum_1_2_out_ap_vld;
wire   [31:0] grp_mmm_accum2_Pipeline_1_fu_103_accum_0_2_out;
wire    grp_mmm_accum2_Pipeline_1_fu_103_accum_0_2_out_ap_vld;
wire    grp_mmm_accum2_Pipeline_ak_fu_111_ap_start;
wire    grp_mmm_accum2_Pipeline_ak_fu_111_ap_done;
wire    grp_mmm_accum2_Pipeline_ak_fu_111_ap_idle;
wire    grp_mmm_accum2_Pipeline_ak_fu_111_ap_ready;
wire   [14:0] grp_mmm_accum2_Pipeline_ak_fu_111_A_address0;
wire    grp_mmm_accum2_Pipeline_ak_fu_111_A_ce0;
wire   [14:0] grp_mmm_accum2_Pipeline_ak_fu_111_B_address0;
wire    grp_mmm_accum2_Pipeline_ak_fu_111_B_ce0;
wire   [31:0] grp_mmm_accum2_Pipeline_ak_fu_111_accum_1_4_out;
wire    grp_mmm_accum2_Pipeline_ak_fu_111_accum_1_4_out_ap_vld;
wire   [31:0] grp_mmm_accum2_Pipeline_ak_fu_111_accum_0_4_out;
wire    grp_mmm_accum2_Pipeline_ak_fu_111_accum_0_4_out_ap_vld;
wire   [31:0] grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_126_p_din0;
wire   [31:0] grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_126_p_din1;
wire   [1:0] grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_126_p_opcode;
wire    grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_126_p_ce;
wire   [31:0] grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_391_p_din0;
wire   [31:0] grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_391_p_din1;
wire    grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_391_p_ce;
reg    grp_mmm_accum2_Pipeline_1_fu_103_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln68_fu_154_p2;
wire    ap_CS_fsm_state3;
reg    grp_mmm_accum2_Pipeline_ak_fu_111_ap_start_reg;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln72_1_fu_284_p1;
wire    ap_CS_fsm_state22;
reg   [8:0] j_fu_54;
wire   [8:0] add_ln69_fu_250_p2;
reg   [31:0] accum_0_1_fu_58;
wire    ap_CS_fsm_state6;
reg   [31:0] accum_1_1_fu_62;
reg   [8:0] i_fu_66;
reg   [16:0] indvar_flatten_fu_70;
wire   [16:0] add_ln68_1_fu_160_p2;
reg   [31:0] grp_fu_126_p0;
reg   [31:0] grp_fu_126_p1;
wire    ap_CS_fsm_state14;
wire   [0:0] icmp_ln69_fu_191_p2;
wire   [8:0] add_ln68_fu_185_p2;
wire   [7:0] trunc_ln72_fu_215_p1;
wire   [15:0] tmp_12_cast_fu_219_p3;
wire   [15:0] zext_ln72_fu_232_p1;
reg    grp_fu_126_ce;
reg    grp_fu_391_ce;
reg   [21:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 22'd1;
#0 grp_mmm_accum2_Pipeline_1_fu_103_ap_start_reg = 1'b0;
#0 grp_mmm_accum2_Pipeline_ak_fu_111_ap_start_reg = 1'b0;
end

top_mmm_accum2_Pipeline_1 grp_mmm_accum2_Pipeline_1_fu_103(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mmm_accum2_Pipeline_1_fu_103_ap_start),
    .ap_done(grp_mmm_accum2_Pipeline_1_fu_103_ap_done),
    .ap_idle(grp_mmm_accum2_Pipeline_1_fu_103_ap_idle),
    .ap_ready(grp_mmm_accum2_Pipeline_1_fu_103_ap_ready),
    .accum_1_1(accum_1_1_fu_62),
    .accum_0_1(accum_0_1_fu_58),
    .accum_1_2_out(grp_mmm_accum2_Pipeline_1_fu_103_accum_1_2_out),
    .accum_1_2_out_ap_vld(grp_mmm_accum2_Pipeline_1_fu_103_accum_1_2_out_ap_vld),
    .accum_0_2_out(grp_mmm_accum2_Pipeline_1_fu_103_accum_0_2_out),
    .accum_0_2_out_ap_vld(grp_mmm_accum2_Pipeline_1_fu_103_accum_0_2_out_ap_vld)
);

top_mmm_accum2_Pipeline_ak grp_mmm_accum2_Pipeline_ak_fu_111(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mmm_accum2_Pipeline_ak_fu_111_ap_start),
    .ap_done(grp_mmm_accum2_Pipeline_ak_fu_111_ap_done),
    .ap_idle(grp_mmm_accum2_Pipeline_ak_fu_111_ap_idle),
    .ap_ready(grp_mmm_accum2_Pipeline_ak_fu_111_ap_ready),
    .accum_1_2_reload(grp_mmm_accum2_Pipeline_1_fu_103_accum_1_2_out),
    .accum_0_2_reload(grp_mmm_accum2_Pipeline_1_fu_103_accum_0_2_out),
    .select_ln68_1(select_ln68_1_reg_364),
    .trunc_ln75_1(trunc_ln75_reg_369),
    .A_address0(grp_mmm_accum2_Pipeline_ak_fu_111_A_address0),
    .A_ce0(grp_mmm_accum2_Pipeline_ak_fu_111_A_ce0),
    .A_q0(A_q0),
    .zext_ln69(select_ln68_reg_359),
    .B_address0(grp_mmm_accum2_Pipeline_ak_fu_111_B_address0),
    .B_ce0(grp_mmm_accum2_Pipeline_ak_fu_111_B_ce0),
    .B_q0(B_q0),
    .accum_1_4_out(grp_mmm_accum2_Pipeline_ak_fu_111_accum_1_4_out),
    .accum_1_4_out_ap_vld(grp_mmm_accum2_Pipeline_ak_fu_111_accum_1_4_out_ap_vld),
    .accum_0_4_out(grp_mmm_accum2_Pipeline_ak_fu_111_accum_0_4_out),
    .accum_0_4_out_ap_vld(grp_mmm_accum2_Pipeline_ak_fu_111_accum_0_4_out_ap_vld),
    .grp_fu_126_p_din0(grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_126_p_din0),
    .grp_fu_126_p_din1(grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_126_p_din1),
    .grp_fu_126_p_opcode(grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_126_p_opcode),
    .grp_fu_126_p_dout0(grp_fu_70_p_dout0),
    .grp_fu_126_p_ce(grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_126_p_ce),
    .grp_fu_391_p_din0(grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_391_p_din0),
    .grp_fu_391_p_din1(grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_391_p_din1),
    .grp_fu_391_p_dout0(grp_fu_74_p_dout0),
    .grp_fu_391_p_ce(grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_391_p_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mmm_accum2_Pipeline_1_fu_103_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln68_fu_154_p2 == 1'd0))) begin
            grp_mmm_accum2_Pipeline_1_fu_103_ap_start_reg <= 1'b1;
        end else if ((grp_mmm_accum2_Pipeline_1_fu_103_ap_ready == 1'b1)) begin
            grp_mmm_accum2_Pipeline_1_fu_103_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mmm_accum2_Pipeline_ak_fu_111_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_mmm_accum2_Pipeline_ak_fu_111_ap_start_reg <= 1'b1;
        end else if ((grp_mmm_accum2_Pipeline_ak_fu_111_ap_ready == 1'b1)) begin
            grp_mmm_accum2_Pipeline_ak_fu_111_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_66 <= 9'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        i_fu_66 <= select_ln68_1_fu_206_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_70 <= 17'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln68_fu_154_p2 == 1'd0))) begin
        indvar_flatten_fu_70 <= add_ln68_1_fu_160_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_fu_54 <= 9'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        j_fu_54 <= add_ln69_fu_250_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        accum_0_1_fu_58 <= grp_mmm_accum2_Pipeline_ak_fu_111_accum_0_4_out;
        accum_1_1_fu_62 <= grp_mmm_accum2_Pipeline_ak_fu_111_accum_1_4_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln72_reg_374 <= add_ln72_fu_236_p2;
        select_ln68_1_reg_364 <= select_ln68_1_fu_206_p3;
        select_ln68_reg_359 <= select_ln68_fu_197_p3;
        trunc_ln75_reg_369 <= trunc_ln75_fu_227_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state13))) begin
        reg_131 <= grp_fu_70_p_dout0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        C_ce0 = 1'b1;
    end else begin
        C_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        C_we0 = 1'b1;
    end else begin
        C_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_mmm_accum2_Pipeline_1_fu_103_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_mmm_accum2_Pipeline_ak_fu_111_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln68_fu_154_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln68_fu_154_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_126_ce = grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_126_p_ce;
    end else begin
        grp_fu_126_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_126_p0 = grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_126_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_126_p0 = reg_131;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_126_p0 = grp_mmm_accum2_Pipeline_ak_fu_111_accum_0_4_out;
    end else begin
        grp_fu_126_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_126_p1 = grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_126_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_126_p1 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_126_p1 = grp_mmm_accum2_Pipeline_ak_fu_111_accum_1_4_out;
    end else begin
        grp_fu_126_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_391_ce = grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_391_p_ce;
    end else begin
        grp_fu_391_ce = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln68_fu_154_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_mmm_accum2_Pipeline_1_fu_103_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_mmm_accum2_Pipeline_ak_fu_111_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = grp_mmm_accum2_Pipeline_ak_fu_111_A_address0;

assign A_ce0 = grp_mmm_accum2_Pipeline_ak_fu_111_A_ce0;

assign B_address0 = grp_mmm_accum2_Pipeline_ak_fu_111_B_address0;

assign B_ce0 = grp_mmm_accum2_Pipeline_ak_fu_111_B_ce0;

assign C_address0 = zext_ln72_1_fu_284_p1;

assign C_d0 = reg_131;

assign add_ln68_1_fu_160_p2 = (indvar_flatten_fu_70 + 17'd1);

assign add_ln68_fu_185_p2 = (i_fu_66 + 9'd1);

assign add_ln69_fu_250_p2 = (select_ln68_fu_197_p3 + 9'd1);

assign add_ln72_fu_236_p2 = (tmp_12_cast_fu_219_p3 + zext_ln72_fu_232_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign grp_fu_70_p_ce = grp_fu_126_ce;

assign grp_fu_70_p_din0 = grp_fu_126_p0;

assign grp_fu_70_p_din1 = grp_fu_126_p1;

assign grp_fu_70_p_opcode = 2'd0;

assign grp_fu_74_p_ce = grp_fu_391_ce;

assign grp_fu_74_p_din0 = grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_391_p_din0;

assign grp_fu_74_p_din1 = grp_mmm_accum2_Pipeline_ak_fu_111_grp_fu_391_p_din1;

assign grp_mmm_accum2_Pipeline_1_fu_103_ap_start = grp_mmm_accum2_Pipeline_1_fu_103_ap_start_reg;

assign grp_mmm_accum2_Pipeline_ak_fu_111_ap_start = grp_mmm_accum2_Pipeline_ak_fu_111_ap_start_reg;

assign icmp_ln68_fu_154_p2 = ((indvar_flatten_fu_70 == 17'd65536) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_191_p2 = ((j_fu_54 == 9'd256) ? 1'b1 : 1'b0);

assign select_ln68_1_fu_206_p3 = ((icmp_ln69_fu_191_p2[0:0] == 1'b1) ? add_ln68_fu_185_p2 : i_fu_66);

assign select_ln68_fu_197_p3 = ((icmp_ln69_fu_191_p2[0:0] == 1'b1) ? 9'd0 : j_fu_54);

assign tmp_12_cast_fu_219_p3 = {{trunc_ln72_fu_215_p1}, {8'd0}};

assign trunc_ln72_fu_215_p1 = select_ln68_1_fu_206_p3[7:0];

assign trunc_ln75_fu_227_p1 = select_ln68_1_fu_206_p3[0:0];

assign zext_ln72_1_fu_284_p1 = add_ln72_reg_374;

assign zext_ln72_fu_232_p1 = select_ln68_fu_197_p3;

endmodule //top_mmm_accum2
