-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_reduce_accum4_ii_is_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_101_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_101_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_101_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_101_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_101_p_ce : OUT STD_LOGIC );
end;


architecture behav of top_reduce_accum4_ii_is_3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (27 downto 0) := "0000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (27 downto 0) := "0000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (27 downto 0) := "0000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (27 downto 0) := "0000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (27 downto 0) := "0000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (27 downto 0) := "0000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (27 downto 0) := "0001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (27 downto 0) := "0010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (27 downto 0) := "0100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (27 downto 0) := "1000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal reg_100 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_start : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_done : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_idle : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_ready : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_3_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_3_0_out_ap_vld : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_2_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_2_0_out_ap_vld : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_1_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_1_0_out_ap_vld : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_0_0_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_0_0_out_ap_vld : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_1145_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_1145_out_ap_vld : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_1041_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_1041_out_ap_vld : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_937_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_937_out_ap_vld : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load33_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load33_out_ap_vld : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_start : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_done : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_idle : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_ready : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_A_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_A_ce0 : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_11_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_11_out_ap_vld : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_10_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_10_out_ap_vld : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_9_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_9_out_ap_vld : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_out_ap_vld : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_ce : STD_LOGIC;
    signal grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal grp_fu_96_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_96_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_96_ce : STD_LOGIC;
    signal ap_return_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_CS_fsm_state28 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state28 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_reduce_accum4_ii_is_3_Pipeline_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        accum_3_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        accum_3_0_out_ap_vld : OUT STD_LOGIC;
        accum_2_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        accum_2_0_out_ap_vld : OUT STD_LOGIC;
        accum_1_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        accum_1_0_out_ap_vld : OUT STD_LOGIC;
        accum_0_0_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        accum_0_0_out_ap_vld : OUT STD_LOGIC;
        accum_load_1145_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        accum_load_1145_out_ap_vld : OUT STD_LOGIC;
        accum_load_1041_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        accum_load_1041_out_ap_vld : OUT STD_LOGIC;
        accum_load_937_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        accum_load_937_out_ap_vld : OUT STD_LOGIC;
        accum_load33_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        accum_load33_out_ap_vld : OUT STD_LOGIC );
    end component;


    component top_reduce_accum4_ii_is_3_Pipeline_accum4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        accum_3_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        accum_2_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        accum_1_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        accum_0_0_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        accum_load_1145_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        accum_load_1041_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        accum_load_937_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        accum_load33_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        A_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        accum_load_11_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        accum_load_11_out_ap_vld : OUT STD_LOGIC;
        accum_load_10_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        accum_load_10_out_ap_vld : OUT STD_LOGIC;
        accum_load_9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        accum_load_9_out_ap_vld : OUT STD_LOGIC;
        accum_load_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        accum_load_out_ap_vld : OUT STD_LOGIC;
        grp_fu_96_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_96_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_96_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_96_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_96_p_ce : OUT STD_LOGIC );
    end component;


    component top_fadd_32ns_32ns_32_8_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66 : component top_reduce_accum4_ii_is_3_Pipeline_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_start,
        ap_done => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_done,
        ap_idle => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_idle,
        ap_ready => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_ready,
        accum_3_0_out => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_3_0_out,
        accum_3_0_out_ap_vld => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_3_0_out_ap_vld,
        accum_2_0_out => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_2_0_out,
        accum_2_0_out_ap_vld => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_2_0_out_ap_vld,
        accum_1_0_out => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_1_0_out,
        accum_1_0_out_ap_vld => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_1_0_out_ap_vld,
        accum_0_0_out => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_0_0_out,
        accum_0_0_out_ap_vld => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_0_0_out_ap_vld,
        accum_load_1145_out => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_1145_out,
        accum_load_1145_out_ap_vld => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_1145_out_ap_vld,
        accum_load_1041_out => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_1041_out,
        accum_load_1041_out_ap_vld => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_1041_out_ap_vld,
        accum_load_937_out => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_937_out,
        accum_load_937_out_ap_vld => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_937_out_ap_vld,
        accum_load33_out => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load33_out,
        accum_load33_out_ap_vld => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load33_out_ap_vld);

    grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78 : component top_reduce_accum4_ii_is_3_Pipeline_accum4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_start,
        ap_done => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_done,
        ap_idle => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_idle,
        ap_ready => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_ready,
        accum_3_0_reload => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_3_0_out,
        accum_2_0_reload => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_2_0_out,
        accum_1_0_reload => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_1_0_out,
        accum_0_0_reload => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_0_0_out,
        accum_load_1145_reload => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_1145_out,
        accum_load_1041_reload => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_1041_out,
        accum_load_937_reload => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load_937_out,
        accum_load33_reload => grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_accum_load33_out,
        A_address0 => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_A_address0,
        A_ce0 => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_A_ce0,
        A_q0 => A_q0,
        accum_load_11_out => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_11_out,
        accum_load_11_out_ap_vld => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_11_out_ap_vld,
        accum_load_10_out => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_10_out,
        accum_load_10_out_ap_vld => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_10_out_ap_vld,
        accum_load_9_out => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_9_out,
        accum_load_9_out_ap_vld => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_9_out_ap_vld,
        accum_load_out => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_out,
        accum_load_out_ap_vld => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_out_ap_vld,
        grp_fu_96_p_din0 => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_din0,
        grp_fu_96_p_din1 => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_din1,
        grp_fu_96_p_opcode => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_opcode,
        grp_fu_96_p_dout0 => grp_fu_101_p_dout0,
        grp_fu_96_p_ce => grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv32_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state28)) then 
                    ap_return_preg <= grp_fu_101_p_dout0;
                end if; 
            end if;
        end if;
    end process;


    grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_ready = ap_const_logic_1)) then 
                    grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_ready = ap_const_logic_1)) then 
                    grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state12))) then
                reg_100 <= grp_fu_101_p_dout0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_done, grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    A_address0 <= grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_A_address0;
    A_ce0 <= grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_A_ce0;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state28 <= ap_CS_fsm(27);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;

    ap_ST_fsm_state2_blk_assign_proc : process(grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_done)
    begin
        if ((grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_done)
    begin
        if ((grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state28)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state28) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state28)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state28)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_return_preg, ap_CS_fsm_state28, grp_fu_101_p_dout0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state28)) then 
            ap_return <= grp_fu_101_p_dout0;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    grp_fu_101_p_ce <= grp_fu_96_ce;
    grp_fu_101_p_din0 <= grp_fu_96_p0;
    grp_fu_101_p_din1 <= grp_fu_96_p1;
    grp_fu_101_p_opcode <= ap_const_lv2_0;

    grp_fu_96_ce_assign_proc : process(grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_ce, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_96_ce <= grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_ce;
        else 
            grp_fu_96_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_96_p0_assign_proc : process(reg_100, grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_out, grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_din0, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state13, ap_CS_fsm_state21)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_96_p0 <= grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_din0;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            grp_fu_96_p0 <= reg_100;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_96_p0 <= grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_out;
        else 
            grp_fu_96_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_96_p1_assign_proc : process(grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_11_out, grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_10_out, grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_9_out, grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_din1, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state13, ap_CS_fsm_state21)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_96_p1 <= grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_grp_fu_96_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            grp_fu_96_p1 <= grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_11_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_96_p1 <= grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_10_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_96_p1 <= grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_accum_load_9_out;
        else 
            grp_fu_96_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_start <= grp_reduce_accum4_ii_is_3_Pipeline_1_fu_66_ap_start_reg;
    grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_start <= grp_reduce_accum4_ii_is_3_Pipeline_accum4_fu_78_ap_start_reg;
end behav;
